version: '3.8'

services:
  wordpress:
    image: bitnami/wordpress-nginx:latest
    container_name: wp_nginx
    restart: always
    ports:
      - "8080:8080"   # WordPress runs on port 8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_SKIP_BOOTSTRAP: "yes"
    volumes:
      - ./wp-content:/bitnami/wordpress/wp-content # Sync plugins/themes to local folder
      - ./nginx-conf:/opt/bitnami/nginx/conf       # Optional: Custom Nginx config

  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
